export const MAP_SPINNING = "MAP_SPINNING";

export const SET_SHOW_NEW_PLACE_PANEL = "SET_SHOW_NEW_PLACE_PANEL";

export const SET_SHOW_COMMENT_PANEL = "SET_SHOW_COMMENT_PANEL";

export const SET_NEW_PLACE_LOCATION = "SET_NEW_PLACE_LOCATION";

export const SET_PLACES = "SET_PLACES";

export const SET_SELECTED_MARKER = "SET_SELECTED_MARKER";

export const CLOSE_SIDE_PANEL = "CLOSE_SIDE_PANEL";

export const SET_LOGGED_USERNAME = "SET_LOGGED_USERNAME";

export const SET_MENU_ON = "SET_MENU_ON";
